/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

@KotlinAssignmentOverloadTarget
public interface ValueProtocol<T> {
    fun changeValue(newValue: T?)
    fun currentValue(): T?
    fun get(): T
    fun assign(value: T)
}

@KotlinAssignmentOverloadTarget
public class Value<T>(var internalValue: T? = null) : ValueProtocol<T> {
    override fun changeValue(newValue: T?) {
        internalValue = newValue
    }
    override fun currentValue(): T? = internalValue
    override fun get(): T = internalValue!!
    override fun assign(value: T) {
        println("Assigning $value")
        this.changeValue(value)
    }
    override fun toString() = "$internalValue"

}
public fun <T> ValueProtocol<T>.assign(value: T?) {
    println("Assigning $value")
    this.changeValue(value)
}
public fun <T> ValueProtocol<T>.assign(value: Value<T>) {
    println("Assigning $value")
    this.changeValue(value.internalValue)
}
