/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

@KotlinAssignmentOverloadTarget
interface ValueProtocol<T> {
    fun changeValue(newValue: T?)
    fun currentValue(): T?
}

class Value<T> : ValueProtocol<T> {
    var internalValue: T? = null
    override fun changeValue(newValue: T?) {
        internalValue = newValue
    }
    override fun currentValue(): T? = internalValue
    fun assign(value: T) {
        this.changeValue(value)
    }

}
fun <T> ValueProtocol<T>.assign(value: T?) {
    this.changeValue(value)
}
fun <T> ValueProtocol<T>.assign(value: Value<T>) {
    this.changeValue(value.internalValue)
}
